name: Release
on:
  push:
    branches:
      - main
      - beta
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: "${{ secrets.COMMIT_KEY }}"
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: foobar
        run: npm pack --dry-run # npx semantic-release
      - name: Getting tag
        id: get_tag
        run: |
          echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
          echo "git tag: ${GIT_TAG}"
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "git tag 2: $TAG"
          echo ::set-output name=tag::$TAG
          echo ::set-output name=tags::${{ env.GIT_TAG }}::$TAGS
          echo "tags: $TAGS"
      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"  
      - name: Upload to s3cdns
        uses: Foxy/foxy-github-action-s3cdn@dev
        with:
          package-name: ${{ steps.vars.outputs.tags }} # optional: Default is repo name.
          tag-name: ${{ env.GIT_TAG }}
        env:
          AWS_S3_CDN_BUCKET_NAME: ${{ secrets.AWS_S3_CDN_BUCKET_NAME }}
          AWS_S3_CDN_KEY_ID: ${{ secrets.AWS_S3_CDN_KEY_ID }}
          AWS_S3_CDN_KEY_SECRET: ${{ secrets.AWS_S3_CDN_KEY_SECRET }}
          SOURCE_DIR: "dist/cdn"


